# 异常处理

> 异常： 失去数据库连接，遇到意外输入等
> 异常处理机制： 异常检测和异常处理两部分


# throw表达式---程序的异常检测
```cpp
if (item1 != item2)
  throw runtime_error("Data must refer to same ISBN")
  //抛出异常将终止当前，并把控制权转移到处理该异常的代码
```
* 类型runtime_error是标准库异常类型的一种，定义在stdexcept头文件中
* 必须初始化 runtime_error


# try 语句块
> try语句块通用语法形式

  ```cpp
  
  try {
	program-statements;}
	catch (expression-declaration){
		handler-statements;
	}catch (expression-declaration){
		handler-statements;
	}catch...
}
  ```
* catch 子语句 ： 异常声明 +处理块
* catch 一旦完成，程序跳转到try语句块最后一个catch子句之后
* try语句块内声明的变量 在块外部无法访问，**在catch子句中也无法访问**

example:
```cpp
while(cin>>item1>>item2){
	try{

	}
	catch(runtime_error err){
		cout<<err.what() << "Try Again?"<<endl;
	}
```


* 其中err 的类型是runtime















